### ISSUE TITLE
G2 jar in Maven Repository

### ISSUE THREAD

**Issue by samuelebe** [Senzing/rest-api-server-java#3]
Hi,

I am able to setup this project in eclipse but however G2 jar is missing in Maven Repository, any idea if there is any other name for this dependency? 
```
<dependency>
     <groupId>com.senzing</groupId>
     <artifactId>g2</artifactId>
       <version>1.0.0-SNAPSHOT</version>
   </dependency>
```

secondly, I have noticed "G2Product" class file in your code, where as it doesn't exist in G2 API's.

Please let us know if you have any details on the above issues?

Thanks

**Comment by samuelebe** [comment]
Platform: Linux
Version: 1.2.18278
Branch name: team_sprint19
Build number: 2018_10_05__02_00

Thanks

**Comment by barrycaceres** [comment]
The REST API Server is currently built with the unreleased team_sprint22 branch.

I will try to test to today with the current release (version 1.4.x / team_sprint21).  If that works, I will provide maven instructions for installing the included g2.jar in your local maven repository and building it (along with an update to the pom.xml in the REST API server to remove the "SNAPSHOT-1.0" from the version dependency).

**Comment by barrycaceres** [comment]
I have tested with the current 1.4.x release (i.e.: team_sprint21) and it seems to work.

This document describes the install process for Linux...
https://github.com/Senzing/hello-senzing-springboot-java/blob/master/doc/debian-based-installation.md#install

Within it you will see a command to `mvn install:install-file ...` to put the included g2.jar into your local maven repository.  However you will need to change this to set the version number correctly.

`mvn install:install-file -Dfile=[path-to-g2-jar] -DgroupId=com.senzing -DartifactId=g2 -Dversion=1.4.0 -Dpackaging.jar`

Here I used simply "version 1.4.0" (rounding down the last part of the version number).

Once you have this, you should be able to use `mvn clean install` to build the REST API server.  The build also works with the unreleased "1.5.0-SNAPSHOT" version of g2.jar.

Make sure you set your LD_LIBRARY_PATH accordingly to find the `[install-path]/g2/lib` and `[install-path]/g2/lib/debian` paths so the native libraries can be found.

**Comment by barrycaceres** [comment]
Please bear in mind that this code is in an "alpha" stage and things are changing.  In fact it has not yet been pushed to the master branch.  We are prepping the code for a "beta" release next month.

**Comment by docktermj** [comment]
Pull requests

1. https://github.com/Senzing/senzing-api-server/pull/7
